services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Создаём volume для сохранения данных
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      # Добавляем SQL-скрипт в папку, автоматически обрабатываемую Postgres
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
volumes:
  postgres_data: 